version: '3'
services:
  flask_app:
    build: ./app
    container_name: getmtiger
    environment:
      - FLASK_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8080:5001"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - flask_app
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    restart: always
