name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
        echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}" >> $GITHUB_ENV
        echo "TEMP_SECRET_KEY=${{ secrets.TEMP_SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: stevexero/getmtiger:latest
        push: true
        platforms: linux/amd64,linux/arm64

    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_IP }}
        username: ${{ secrets.LINODE_USERNAME }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        script: |
          docker pull stevexero/getmtiger:latest
          docker stop getmtiger || true
          docker rm getmtiger || true
          docker run -d --name getmtiger -p 80:5000 \
          -e ASSET_TIGER_USERNAME='${{ secrets.ASSET_TIGER_USERNAME }}' \
          -e ASSET_TIGER_PASSWORD='${{ secrets.ASSET_TIGER_PASSWORD }}' \
          -e ASSET_TIGER_FILENAME='${{ secrets.ASSET_TIGER_FILENAME }}' \
          -e ASSET_TIGER_FILEPATH='${{ secrets.ASSET_TIGER_FILEPATH }}' \
          -e ASSET_TIGER_LOGIN_URL='${{ secrets.ASSET_TIGER_LOGIN_URL }}' \
          -e ASSET_TIGER_DASHBOARD_URL='${{ secrets.ASSET_TIGER_DASHBOARD_URL }}' \
          -e ASSET_TIGER_EXPORT_URL='${{ secrets.ASSET_TIGER_EXPORT_URL }}' \
          -e ASSET_TIGER_IMPORT_URL='${{ secrets.ASSET_TIGER_IMPORT_URL }}' \
          -e ENVIRONMENT='${{ secrets.ENVIRONMENT }}' \
          -e TEMP_SECRET_KEY='${{ secrets.TEMP_SECRET_KEY }}' \
          -e SUPABASE_URL='${{ secrets.SUPABASE_URL }}' \
          -e SUPABASE_SERVICE_ROLE_KEY='${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}' \
          stevexero/getmtiger:latest
